### ISSUE TITLE
How can the hero image be displayed

### ISSUE THREAD

**Issue by abdellahrk** [manuxi/SuluNewsBundle#2]
Hello, when accessing the news item, only the images from the gallery are shown. How can the hero image be shown?
@manuxi

**Comment by manuxi** [comment]
If you dump the current news ({{ dump(news) }}) you should see what's in it. news.image is what you're asking for.
I usually use it this way:
```
{% if news.image %}
                        {% set image = sulu_resolve_media(news.image.id, app.request.locale) %}
                        <img src="{{ asset(image.thumbnails['x200-inset']) }}"  alt="{{ news.title }}">
                    {% endif %}
```

**Comment by abdellahrk** [comment]
Thank you @manuxi, I found that out later today. Thank you for the amazing work.

**Comment by manuxi** [comment]
Please feel free to retell ;)
