### ISSUE TITLE
The package is breaking the preview/edit page

### ISSUE THREAD

**Issue by abdellahrk** [manuxi/SuluNewsBundle#4]
The package is breaking the preview page.
I cannot reproduce this but removing the package and its dependencies makes the preview page to come back.

**Comment by manuxi** [comment]
I can not reproduce this either. Pleas supply with more information.

**Comment by abdellahrk** [comment]
Nothing is being logged @manuxi,
I removed from the other project and this is a new installation. I followed the installation instructions but now when I create a new item, it breaks the preview/edit page of the entire admin backend.

**Comment by abdellahrk** [comment]
In the browser console I get `Error: The route "sulu_automation.get_task_count" does not exist.` @manuxi

**Comment by abdellahrk** [comment]
This bundle requires the Automation Bundle to be configured as it does not do that automatically. [Automation Bundle](https://github.com/sulu/SuluAutomationBundle/blob/2.1/Resources/doc/installation.md)

**Comment by manuxi** [comment]
Since the AutomationBundle was installed already at the time I've created the NewsBundle I didn't face that problem. I'll update the docs. Only the routes are missing? Thank you for reporting.

**Comment by abdellahrk** [comment]
Yes the routes. Also, I suggest you install the bundle on a new Sulu project and test it. 
Talking about this issue #3, the NewsTranslationBundle is not registered as a service thus it does not work with autowiring.

**Comment by abdellahrk** [comment]
It's okay. It's good you have opened the discussion. This is not intended to be a one-on-one support. But I think new packages require users who at the same time are testers. 
Thank you for your time.
