### ISSUE TITLE
View templates extends an inexistent template

### ISSUE THREAD

**Issue by abdellahrk** [manuxi/SuluNewsBundle#5]
The view extends the `body.html.twig` and this template does not exist. Could this not extend the default base template?

**Comment by manuxi** [comment]
I did this to fit my needs. If you need it in another way please place it in your templates folder as it's done the common way.
I just opened up the discussions, so please ask for questions. Or head to the sulu slack.

**Comment by manuxi** [comment]
put the template in templates/bundles/SuluNewsBundle/news.html.twig and extend from what you need.
Since the base.html.twig is used in common cases I'll consider extend from it.
